spring:
  cloud:
    gcp:
      credentials:
        location: ${hedera.dedupe.credentialsLocation}
      bigquery:
        projectId: ${hedera.dedupe.projectId}
        datasetName: ${hedera.dedupe.datasetName}