spring:
  cloud:
    gcp:
      projectId: ${hedera.dedupe.projectId}
      credentials:
        location: ${hedera.dedupe.credentialsLocation}
      bigquery:
        datasetName: ${hedera.dedupe.datasetName}
